### ISSUE TITLE
Correcciones ejercicio `curriculum en inglés`

### ISSUE THREAD

**Issue by Xaviju** [marcomassala/programmation#1]
Hola Marco, te paso las correcciones al ejercicio:

Estos estilos no son correctos, porque lo elementos deberían ser hermanos entre ellos, no uno hijo de otro. En cualquier caso, no le des importancia, a partir de esta semana empezaremos a aprender estilos y lo entenderás mejor.

https://github.com/marcomassala/programmation/blob/5f2e35100bc8b463711bc9c67a4fdb9086fb56a4/Curriculum%20en%20Ingl%C3%A9s.html#L10

En general todo lo demás está bien, pero hemos aprendido muchas cosas y el objetivo es que creaseis varias páginas enlazadas con todo lo que hemos visto de HTML para que probáseis a hacer cosas más complejas y experimentar un poco. 

Te animo a que lo intentes, revisa [la tarea que puso Ricardo](https://mfrcodingproject.slack.com/archives/CGXC4PMS9/p1554412184009100),  y me comprometo a revisarlo y ayudarte.

Ánimo, si necesitas ayuda, dímelo.

**Comment by marcomassala** [comment]
Muchas gracias Profe.
